services:
  db:
    image: postgres:latest
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_DB: ${PG_NAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data 
      - ./initdb:/docker-entrypoint-initdb.d
    networks:
      - db_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    networks:
      - db_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  datainserter:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file: .env
    ports:
      - "8080:8080"  
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    networks:
      - db_network
    

 
volumes:
  pgdata:
  redisdata:
networks:
  db_network: